apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: 'osprey.kt.secure.lab.us-west-2.hcom.cloud'
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  name: osprey-external
  namespace: osprey
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 10.0.0.0/8
  - 172.0.0.0/8
  - 91.232.36.4/32
  ports:
  - name: osprey
    protocol: TCP
    port: 443
    targetPort: 5555
  selector:
    app: osprey
