apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kev-pods-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kev-pods
subjects:
  - kind: User
    name: kevtaylor@kt
