apiVersion: v1
kind: Service
metadata:
  name: @dexService@
  namespace: @namespace@
spec:
  type: ClusterIP
  ports:
  - name: dex
    protocol: TCP
    port: @dexPort@
    targetPort: @dexPort@
  - name: dex-metrics
    protocol: TCP
    port: @dexTelemetryPort@
    targetPort: @dexTelemetryPort@
  selector:
    app: @dexApp@
