---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dex-service-account
  namespace: osprey
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
  labels:
    app: dex
  name: dex-deployment
  namespace: osprey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dex
    spec:
      serviceAccount: dex-service-account
      volumes:
      - name: dex-config
        configMap:
          name: dex-config
      - name: dex-web-templates
        configMap:
          name: dex-web-templates
      - name: ssl
        secret:
          secretName: osprey-ssl
      - name: dex-storage
        emptyDir: {}

      containers:
      - name: dex
        image: quay.io/coreos/dex:v2.10.0
        command:
        - /usr/local/bin/dex
        args:
        - serve
        - /etc/dex/cfg/config.yml

        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 5556
            scheme: HTTPS
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 5556
            scheme: HTTPS

        ports:
        - name: dex
          containerPort: 5556
          protocol: TCP
        - name: dex-metrics
          containerPort: 5557
          protocol: TCP

        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 150m
            memory: 256Mi

        volumeMounts:
        - mountPath: /etc/dex/cfg
          name: dex-config
        - mountPath: /data
          name: dex-storage
        - mountPath: /ssl
          name: ssl
          readOnly: true
        - mountPath: /web/templates/approval.html
          name: dex-web-templates
          subPath: approval.html
        - mountPath: /web/templates/error.html
          name: dex-web-templates
          subPath: error.html
        - mountPath: /web/templates/footer.html
          name: dex-web-templates
          subPath: footer.html
        - mountPath: /web/templates/header.html
          name: dex-web-templates
          subPath: header.html
        - mountPath: /web/templates/login.html
          name: dex-web-templates
          subPath: login.html
        - mountPath: /web/templates/oob.html
          name: dex-web-templates
          subPath: oob.html
        - mountPath: /web/templates/password.html
          name: dex-web-templates
          subPath: password.html
