apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: osprey
spec:
  type: ClusterIP
  ports:
  - name: dex
    protocol: TCP
    port: 5556
    targetPort: 5556
  - name: dex-metrics
    protocol: TCP
    port: 5557
    targetPort: 5557
  selector:
    app: dex
